Repository arduino-libraries/Arduino_Braccio_plusplus, pull requests merged in 2022-02, with the labels that each got.

#52 Fix broken links to library workflows/badges.
  README.md
Labels: topic: documentation, type: enhancement

#54 Fix: Change title of README to actual library name.
  README.md
Labels: topic: documentation, type: enhancement

#53 Fix: Do not require all servos to be connected when running `Factory_Set_Initial_Servo_Position`
  examples/Tools/Factory_Set_Initial_Servo_Position/Factory_Set_Initial_Servo_Position.ino
  src/Braccio++.cpp
  src/Braccio++.h
Labels: type: enhancement, topic: code

#57 Add success message when driving of a servo to the initial position succeeds.
  examples/Tools/Factory_Set_Initial_Servo_Position/Factory_Set_Initial_Servo_Position.ino
Labels: type: enhancement, topic: infrastructure

#56 Switch to variant of "Compile Examples" workflow for public repos
  .github/workflows/compile-examples.yml
  .github/workflows/report-size-deltas.yml
  README.md
Labels: topic: infrastructure

#58 Replace default parameter value with inline function definition for `begin`.
  src/Braccio++.h
Labels: type: enhancement, topic: code

#60 Fix: Capture a new start value - otherwise the loop will terminate prematurely due to a wrong timeout value.
  examples/Tools/Factory_Set_Initial_Servo_Position/Factory_Set_Initial_Servo_Position.ino
Labels: type: enhancement, topic: code

#61 Fix lvgl crash on startup with ArduinoCore-mbed >= 2.7.2
  examples/Braccio_Basic/Braccio_Basic.ino
  examples/LCD_Custom_Menu/LCD_Custom_Menu.ino
  examples/LCD_Menu_Joystick/LCD_Menu_Joystick.ino
  examples/LCD_Motors/LCD_Motors.ino
  src/Braccio++.cpp
  src/Braccio++.h
Labels: type: imperfection, type: enhancement, topic: code

#62 Encapsulate all LVGL library calls within examples/tutorials with lvgl_lock/lvgl_unlock.
  examples/tutorials/lessons/01-programming-the-braccio-display/01_creating_a_button/01_creating_a_button.ino
  examples/tutorials/lessons/01-programming-the-braccio-display/02_designing_the_button/02_designing_the_button.ino
  examples/tutorials/lessons/01-programming-the-braccio-display/03_creating_a_menu/03_creating_a_menu.ino
  examples/tutorials/lessons/01-programming-the-braccio-display/04_testing_it_out/04_testing_it_out.ino
  examples/tutorials/lessons/01-programming-the-braccio-display/05_display_challenge/05_display_challenge.ino
  examples/tutorials/lessons/02-navigatting-the-display-menu/02_handling_events_in_the_menu/02_handling_events_in_the_menu.ino
  examples/tutorials/lessons/02-navigatting-the-display-menu/03_navigate_challenge_I/03_navigate_challenge_I.ino
  examples/tutorials/lessons/02-navigatting-the-display-menu/04_navigate_challenge_II/04_navigate_challenge_II.ino
  examples/tutorials/lessons/04-integration-of-previous-learnings/01_playing_with_a_joint_angle_gauge/01_playing_with_a_joint_angle_gauge.ino
  examples/tutorials/lessons/04-integration-of-previous-learnings/02_selecting_the_motor_in_the_LCD_menu/02_selecting_the_motor_in_the_LCD_menu.ino
  examples/tutorials/lessons/04-integration-of-previous-learnings/03_learnings_challenge_I/03_learnings_challenge_I.ino
  examples/tutorials/lessons/04-integration-of-previous-learnings/04_learnings_challenge_II/04_learnings_challenge_II.ino
Labels: type: enhancement, topic: code
